### ISSUE TITLE
Question - Searching of encrypted PDF files

### ISSUE THREAD

**Issue by milanv74** [tgotic/xPDFSearch#3]
Hello,
please is possible to configure the xPDFSearch extension in Total Commander anyhow to be able to search encrypted PDF files (files for which is necessary to insert a password for their opening /not a password for editing/)?
Thank you for your answer.

**Comment by tgotic** [comment]
Hello,
Current version of xPDFSearch doesn't have such functionality. Maybe one of the next versions.

**Comment by tgotic** [comment]
Hello,
Please try v1.43. with "Protected" field. This field is marked as "Yes" if PDF cannot be open without password. There is also Protected attribute, marked as X.

**Comment by tgotic** [comment]
Added support for certificate protected PDF files.
