### ISSUE TITLE
1.43 bugs

### ISSUE THREAD

**Issue by Monarchtest** [tgotic/xPDFSearch#4]
In the new version 1.43, compared to version 1.42, the following fields no longer work correctly:
"Page Width" - in the old version 210 mm is displayed, in the new one 216 mm (PDF files are the same)
"Page Height" - in the old version 297 mm is displayed, in the new one 279 mm (PDF files are the same)
"Document Start" - not supporting the Cyrillic alphabet (in v1.42 -supported)
"First Row" - not supporting the Cyrillic alphabet (in v1.42 -supported)
Please correct me if it's not difficult.

**Comment by tgotic** [comment]
Please try v1.44. Bugs should be fixed.

**Comment by Monarchtest** [comment]
In version 1.44, all fields are displayed correctly. Thank you!
